### ISSUE TITLE
System monitors doesn't works on Mac M1

### ISSUE THREAD

**Issue by rastaman** [rastaman/Homedash2#9]
While the project compile with OpenJDK 1.17 and `oshi` 6.4.1, it fails to run with the following error:

```
14:22:16.835 [main] INFO  com.ftpix.homedash.app.PluginModuleMaintainer - Instance doesn't exist, recreating it
Exception in thread "main" java.lang.NoSuchMethodError: 'com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)'
	at com.sun.jna.platform.mac.SystemB.<clinit>(SystemB.java:40)
	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:52)
	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:40)
	at oshi.hardware.platform.mac.MacCentralProcessor.initProcessorCounts(MacCentralProcessor.java:119)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65)
	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(MacCentralProcessor.java:47)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.createProcessor(MacHardwareAbstractionLayer.java:42)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at com.ftpix.homedash.plugins.SystemInfoPlugin.init(SystemInfoPlugin.java:84)
	at com.ftpix.homedash.plugins.Plugin.setModule(Plugin.java:353)
	at com.ftpix.homedash.app.PluginModuleMaintainer.getPluginForModule(PluginModuleMaintainer.java:70)
	at com.ftpix.homedash.app.PluginModuleMaintainer.lambda$getAllPluginInstances$0(PluginModuleMaintainer.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.ftpix.homedash.app.PluginModuleMaintainer.getAllPluginInstances(PluginModuleMaintainer.java:95)
	at com.ftpix.homedash.app.controllers.PluginUrlController.defineEndPoints(PluginUrlController.java:19)
	at com.ftpix.homedash.app.Endpoints.define(Endpoints.java:45)
	at com.ftpix.homedash.app.App.main(App.java:112)
```

**Comment by rastaman** [comment]
That is perhaps also related to my use of a M1 Mac:
```
❯ mvn -pl web exec:java -Dconfig.file=../homedash-deploy/homedash.properties
...
[qtp1514132942-28] WARN org.eclipse.jetty.server.HttpChannel - /add-module/com.ftpix.homedash.plugins.harddisk.HarddiskPlugin
java.lang.UnsatisfiedLinkError: /private/var/folders/qd/m4_vf89s7053tw49zdgch8x00000gn/T/jna-279551902/jna11996012628359397373.tmp: dlopen(/private/var/folders/qd/m4_vf89s7053tw49zdgch8x00000gn/T/jna-279551902/jna11996012628359397373.tmp, 0x0001): \
tried: '/private/var/folders/qd/m4_vf89s7053tw49zdgch8x00000gn/T/jna-279551902/jna11996012628359397373.tmp'\
 (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), \
'/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/qd/m4_vf89s7053tw49zdgch8x00000gn/T/jna-279551902/jna11996012628359397373.tmp' (no such file), 
\
'/private/var/folders/qd/m4_vf89s7053tw49zdgch8x00000gn/T/jna-279551902/jna11996012628359397373.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
```

**Comment by rastaman** [comment]
This works by ensuring only the right version of JNA is loaded and packaged (the one of OSHI). Issue with Mac Siicon remains but it works on one of my linux boxes, renaming.
